// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRLXQxSdXwkPsB5Ulx2LJH4TJlerczRwM',
    appId: '1:347109444058:web:1fddbb10994cfd59b4d8e3',
    messagingSenderId: '347109444058',
    projectId: 'project-infosis',
    authDomain: 'project-infosis.firebaseapp.com',
    storageBucket: 'project-infosis.firebasestorage.app',
    measurementId: 'G-S5YDPM3CY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlbAFAp8VqIWOb7XFTa2pBD5Fk7763Tao',
    appId: '1:347109444058:android:77a35c2ddc51b363b4d8e3',
    messagingSenderId: '347109444058',
    projectId: 'project-infosis',
    storageBucket: 'project-infosis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UyF8hE59ES78seVwmRHY_ZPOD6YfPT0',
    appId: '1:347109444058:ios:cb1c29aa79d9e379b4d8e3',
    messagingSenderId: '347109444058',
    projectId: 'project-infosis',
    storageBucket: 'project-infosis.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UyF8hE59ES78seVwmRHY_ZPOD6YfPT0',
    appId: '1:347109444058:ios:cb1c29aa79d9e379b4d8e3',
    messagingSenderId: '347109444058',
    projectId: 'project-infosis',
    storageBucket: 'project-infosis.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRLXQxSdXwkPsB5Ulx2LJH4TJlerczRwM',
    appId: '1:347109444058:web:f07073a67855c83bb4d8e3',
    messagingSenderId: '347109444058',
    projectId: 'project-infosis',
    authDomain: 'project-infosis.firebaseapp.com',
    storageBucket: 'project-infosis.firebasestorage.app',
    measurementId: 'G-N99RKBYQQL',
  );

}
